[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["cd apps/api && yarn install"]

[phases.build]
cmds = ["cd apps/api && yarn build"]

[start]
cmd = "cd apps/api && yarn start:prod"

